import { Footer } from "@/components/footer";
import { Navbar } from "@/components/navbar";
import { NoiseOverlay } from "@/components/noise-overlay";
import { ThemeProvider } from "@/components/theme-provider";
import { ReactLenis } from "lenis/react";
import type { Metadata } from "next";
import { Funnel_Display, Geist, Geist_Mono } from "next/font/google";
import AnimatedCursor from "react-animated-cursor";

import "./globals.css";

const geistSans = Geist({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-geist-sans",
});
const geistMono = Geist_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-geist-mono",
});
const funnelDisplay = Funnel_Display({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-funnel-display",
});

export const metadata: Metadata = {
  title: "Szami",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactLenis root>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${funnelDisplay.variable} antialiased font-sans bg-purple-500 overscroll-none`}
        >
          <NoiseOverlay />
          <AnimatedCursor
            color="255,255,255"
            showSystemCursor
            innerSize={0}
            outerSize={80}
            outerAlpha={0.1}
            outerScale={2}
            outerStyle={{
              filter: "blur(24px)",
              zIndex: 40,
            }}
          />
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            themes={["dark"]}
            forcedTheme="dark"
            disableTransitionOnChange
          >
            <Navbar />
            {children}
            <Footer />
          </ThemeProvider>
        </body>
      </html>
    </ReactLenis>
  );
}
